# Generated by Django 4.2.4 on 2023-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reporter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='category',
            field=models.IntegerField(default=1, verbose_name=[(1, 'ข่าวกีฬา'), (2, 'ข่าวบันเทิง'), (3, 'ข่าวอาชญากรรม')]),
        ),
    ]
