# Generated by Django 4.2.4 on 2023-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.IntegerField(choices=[(1, 'ข่าวกีฬา'), (2, 'ข่าวบันเทิง'), (3, 'ข่าวการเมือง')], default=1),
        ),
    ]
