# Generated by Django 4.1.3 on 2023-09-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_new_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Art',
        ),
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': 'Art', 'verbose_name_plural': 'Arts'},
        ),
    ]
