# Generated by Django 4.1.3 on 2023-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_new_art_alter_art_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.IntegerField(choices=[(1, 'ข่าวกีฬา'), (2, 'ข่าวบันเทิง'), (3, 'ข่าวการเมือง'), (4, 'ข่าวอาชญากรรม')], default=1),
        ),
    ]
