# Generated by Django 4.1.3 on 2023-09-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_category_alter_art_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.IntegerField(choices=[(1, 'ข่าวกีฬา'), (2, 'ข่าวบันเทิง'), (3, 'ข่าวการเมือง'), (4, 'ข่าวอาชญากรรม')], default=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
